### ISSUE TITLE
Unable to do the sudo pacman -S tor

### ISSUE THREAD

**Issue by Ethanjohnc1** [WilliamHYZhang/Reddit-Bot-Account-Maker#4]
It says pacman is not a command
![Screenshot from 2023-07-23 21-34-41](https://github.com/WilliamHYZhang/Reddit-Bot-Account-Maker/assets/140349479/0271b130-9922-436f-a6b1-f25693ef119d)

**Comment by Ethanjohnc1** [comment]
![Screenshot from 2023-07-23 21-34-41](https://github.com/WilliamHYZhang/Reddit-Bot-Account-Maker/assets/140349479/65c199ae-25c8-4ae4-a370-250858103ce6)

**Comment by Ethanjohnc1** [comment]
![Screenshot from 2023-07-23 21-35-26](https://github.com/WilliamHYZhang/Reddit-Bot-Account-Maker/assets/140349479/7fbe776d-c075-4c59-9fa3-02fc643949ae)

**Comment by WilliamHYZhang** [comment]
Seems like something on your end when trying to install tor? Try using a different package manager
